
-- Use the ref() function to manage dependencies.
-- Learn more about ref() and other built in functions here: https://cloud.google.com/dataform/docs/dataform-core

config { 
        type: "view",
        name: "test_view",
        description : '',
        assertions: {
            rowConditions: [
                'num > 0',
            ] 
        }
 }

-- The execution will fail if the column num est less than zero after running the select query

SELECT * from ${ref("test")}
